server:
  tomcat:
    uri-encoding: UTF-8
  port: 80

logging:
  level:
    org.springframework.web: ERROR
    io.kauri:  TRACE
    net.consensys: TRACE

#For IPFS-Doc-Persister Service
ipfs-store:
  storage:
    type: IPFS
    host: ${IPFS_HOST:localhost}
    port: ${IPFS_PORT:5001}
    
  index:
    type: ELASTICSEARCH
    host: ${ELASTIC_HOST:localhost}
    port: ${ELASTIC_PORT:9300}
    additional:
      clusterName: ${ELASTIC_CLUSTERNAME:docker-cluster}
      indexNullValue: true
      
  pinning:
    strategies:
      - 
        id: ipfs_node
        type: native
        host: ${IPFS_HOST:localhost}
        port: ${IPFS_PORT:5001}
      - 
        id: ipfs_cluster
        type: ipfs_cluster
        enable: ${IPFS_CLUSTER_ENABLE:false}
        host: ${IPFS_CLUSTER_HOST:localhost}
        port: ${IPFS_CLUSTER_PORT:9094}

  api-spec:
     base: /ipfs-store
     store:
        uri: /store
     index:
        uri: /index
     store_index:
        uri: /store_index
     search:
        uri: /search/{index}
     fetch:
        uri: /fetch/{index}/{hash}
     config_index:
        uri: /config/index/{index}

ipfs-document-persiter:
  indexes:
    blogpost:
      name: blogpost
      fields: id,title,content,user
      fullTextFields: title,content

# For Kafka
zookeeper:
  address: ${ZOOKEEPER_ADDRESS:localhost:2181}
kafka:
  bootstrap:
    addresses: ${KAFKA_ADDRESSES:localhost:9092}
  topic:
    contractEvents: contract-events

eventeum:
  url: http://eventeum:8060/api/rest/v1/
  contractAddress: 0xe5ed74837c78bef362180c4bf91c964c68ccb5c5
     